---
- name: Update apt cache and install unzip and curl
  apt:
    name:
      - unzip
      - curl
    state: present
    update_cache: yes

- name: Check if AWSCLI is installed
  stat:
    path: "{{ awscli_bin }}"
  register: awscli_installed

- name: Download AWS CLI v2 bundle
  get_url:
    url: "{{ awscli_url }}"
    dest: "{{ awscli_zip }}"
    mode: '0644'
  when: not awscli_installed.stat.exists

- name: Create installer directory
  file:
    path: "{{ awscli_installer_dir }}"
    state: directory
    mode: '0755'
  when: not awscli_installed.stat.exists

- name: Extract downloaded zip
  unarchive:
    src: "{{ awscli_zip }}"
    dest: "{{ awscli_installer_dir }}"
    remote_src: yes
  when: not awscli_installed.stat.exists

- name: Run AWS CLI installer
  command: "{{ awscli_installer_dir }}/aws/install"
  args:
    creates: "{{ awscli_bin }}"
