---
- name: Update apt cache and install unzip and curl
  apt:
    name:
      - unzip
      - curl
    state: present
    update_cache: yes

- name: Download AWS CLI v2 bundle
  get_url:
    url: "{{ awscli_url }}"
    dest: "{{ awscli_zip }}"
    mode: '0644'

- name: Create installer directory
  file:
    path: "{{ awscli_installer_dir }}"
    state: directory
    mode: '0755'

- name: Extract downloaded zip
  unarchive:
    src: "{{ awscli_zip }}"
    dest: "{{ awscli_installer_dir }}"
    remote_src: yes

- name: Run AWS CLI installer
  command: "{{ awscli_installer_dir }}/aws/install"
  args:
    creates: /usr/local/bin/aws
